version: '3.8'  # Specifies the Docker Compose version

services:
  web:
    build: 
      context: .  # Specifies the directory containing Dockerfile and source code
      dockerfile: Dockerfile.dev  # Specifies the Dockerfile to use
    ports:
      - "3000:3000"  # Maps port 3000 of the container to port 3000 on the host
    volumes:
      - /app/node_modules # Do not map the node_modules folder
      - .:/app  # Maps the current directory to /app in the container
    working_dir: /app  # Sets the working directory inside the container
    # command: npm start  # Command to run upon starting the container
    environment:
      - NODE_ENV=development  # Environment variables
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    working_dir: /app
    command: ["npm", "run", "test"]
